services:
  amr-demo:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: demo
  amr-gui:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: gui
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
